% Sweave(file = './readVcf.Rnw')
% , driver = cacheSweaveDriver)
\documentclass[10pt]{article}
<<echo=FALSE>>=
  options(width=70, continue = " ")
@ 
\SweaveOpts{eps=FALSE,echo=TRUE,figs.only=TRUE,keep.source=FALSE, prefix.string=figures/readVcf}
\usepackage{fullpage}
\usepackage{times}
\usepackage[colorlinks=TRUE,urlcolor=blue,citecolor=blue]{hyperref}
%\title{TITLE}
%\author{Sam}
%\date{\today}
%\input{/home/bst/student/syounkin/jhsph/latex/sgy}
%\input{/home/sgy/jhsph/latex/sgy}
\begin{document}
\setlength{\parskip}{0.2\baselineskip}
\setlength{\parindent}{0pt}
%\maketitle
Today is \today.
%<<cachedir, echo=FALSE>>=
%setCacheDir( path = './cache/' )
%@ 
<<packages, cache = FALSE>>=
rm(list=ls())
source("~/jhsph/R/reload.R")
library("vcf2R")
library("GGtools")
data(targets.hg19)
seqlevels(targets.hg19.gr) <- substr(seqlevels(targets.hg19.gr),4,100)
@ 
<<make, cache = FALSE>>=
for( locus in names(targets.hg19.gr) ){
for( eth in c("european","chinese","filipino") ){
  fl <- paste0("/thumper/ctsa/beaty/targeted_seq/regional/", locus, "-", eth, "-all.recode.vcf.gz" )
  sm <- vcf2sm(Rsamtools::TabixFile(fl), gr=targets.hg19.gr[locus,], nmetacol=9L)
  save( sm, file = paste0("/home/bst/student/syounkin/R/packages/vcf2R/data/", locus, "-", eth, "-all.sm.RData" ) )
}
}
@ 
\end{document}

