% Sweave(file = './tdt.Rnw')
% , driver = cacheSweaveDriver)
\documentclass[10pt]{article}
<<echo=FALSE>>=
  options(width=70, continue = " ")
@ 
\SweaveOpts{eps=FALSE,echo=TRUE,figs.only=TRUE,keep.source=FALSE, prefix.string=figures/tdt}
\usepackage{fullpage}
\usepackage{times}
\usepackage[colorlinks=TRUE,urlcolor=blue,citecolor=blue]{hyperref}
\title{8q24 in the European sample: A pipeline for targeted sequence analysis}
\author{Samuel G. Younkin}
\date{\today}
%\input{/home/bst/student/syounkin/jhsph/latex/sgy}
\input{/home/sgy/jhsph/latex/sgy}
\begin{document}
\setlength{\parskip}{0.2\baselineskip}
\setlength{\parindent}{0pt}
%\maketitle
%<<cachedir, echo=FALSE>>=
%setCacheDir( path = './cache/' )
%@ 
<<rmandreload, echo = FALSE>>=
rm(list=ls())
source("~/jhsph/R/reload.R")
@ 
<<packages>>=
library("vcf2R")
library("snpStats")
## data("ABCA4-european-all.sm")
## data("BMP4-european-all.sm")
## data("FGFR2-european-all.sm")
## data("FOXE1-european-all.sm")
## data("IRF6-european-all.sm")
## data("MAFB-european-all.sm")
## data("MSX1-european-all.sm")
## data("NOG-european-all.sm")
## data("NTN1-european-all.sm")
## data("PAX7-european-all.sm")
## data("PTCH1-european-all.sm")
## data("VAX1-european-all.sm")
## data("8q24-chinese-all.sm")
data("ABCA4-chinese-all.sm")
data(ped, package= "vcf2R" )
@
After loading the necessary packages and data we first make sure that the pedigree data frame contains fields F, M and O for father, mother and offspring ids.  Note that these ids should match those in the vcf file.
<<pedigree>>=
ped.df <- with(ped.df, {
  data.frame( ped = ped, id = id, father = fid, mother = mid, sex = sex, affected = affected + 1 )
})
pedigreeInfo <- subset( ped.df, !is.na(id) )
rownames(pedigreeInfo) <- pedigreeInfo$id 
@ 
<<maf>>=
maf <- colSums(as(sm, "numeric"), na.rm=TRUE)/colSums(!is.na(sm))/2
maf <- ifelse( maf > 0.5, 1- maf, maf )
sub <- which( maf >= 0.05)
@ 
<<tdt>>=
tdt.obj <- tdt.snp(data = pedigreeInfo, snp.data = sm, snp.subset = sub )
@ 
\begin{figure}
<<qq-8q24, fig = TRUE>>=
qq.chisq(chi.squared(tdt.obj, 1), df = 1)
@ 
\end{figure}
\end{document}
