% Sweave(file = "./vcf2R.Rnw", driver = cacheSweaveDriver )
\documentclass[10pt]{article}
<<echo=FALSE>>=
  options(width=70, continue = " ")
@ 
\SweaveOpts{eps=FALSE,echo=TRUE,figs.only=TRUE,keep.source=FALSE, prefix.string=figures/vcf2R}
\usepackage{fullpage}
\usepackage{times}
\usepackage[colorlinks=TRUE,urlcolor=blue,citecolor=blue]{hyperref}
%\title{CQN (Conditional Quantile Normalization)}
%\author{Kasper Daniel Hansen \\ \texttt{khansen@jhsph.edu}
%\and
%Zhijin Wu \\ \texttt{zhijin\_wu@brown.edu}}
%\date{Modified: April 29, 2012.  Compiled: \today}
\input{/home/sgy/jhsph/latex/sgy}
\begin{document}
\setlength{\parskip}{0.2\baselineskip}
\setlength{\parindent}{0pt}
%\maketitle
Today is \today.
%<<cachedir, echo=FALSE>>=
%setCacheDir( path = './cache/' )
%@ 
<<packages, cache = FALSE>>=
library("vcf2R")
library("GenomicRanges")
library("BSgenome.Hsapiens.UCSC.hg19")
@ 
\section{Targeted Loci}
<<pos>>=
file = "/home/sgy/jhsph/targeted-sequencing/repo/vcf2R/inst/extdata/snvs.fixed_header.frq"
pos.df <- frq2pos( file )
head(pos.df)
@ 
<<loci>>=
with( pos.df, table(chr) )
pos.gr <- with( pos.df, GRanges( seqnames = paste("chr", chr, sep = ""), ranges = IRanges( start = pos, end = pos ), strand = "+" ) )
seqlengths(pos.gr) <- seqlengths(Hsapiens)[levels(seqnames(pos.gr))]
start(pos.gr) <- start(pos.gr) - 10e3
end(pos.gr) <- end(pos.gr) + 10e3
loci <- reduce(pos.gr)
start(loci) <- start(loci) + 10e3
end(loci) <- end(loci) - 10e3
@ 
\newpage
<<width>>=
val <- data.frame( n.snps = countOverlaps(loci, pos.gr), kb = width(loci)/1e3 )
values(loci) <- val
names(loci) <- c("PAX7", "ABCA4", "IRF6", "VAX1", "FGFR2", "BMP4", "NTN1", "NOG", "MAFB", "MSX1", "8q24", "PTCH1", "FOXE1")
loci
sum(width(loci))/1e6
with( values(loci), sum(n.snps) )
@ 
\section{Hardy-Weinberg Equilibrium}
<<hwe2R>>=
file = "/home/sgy/jhsph/targeted-sequencing/repo/vcf2R/inst/extdata/snvs.fixed_header.hwe"
hwe.df <- hwe2R( file = file )
head(hwe.df)
@
%\begin{figure}
%<<hwe-hist, fig = TRUE, echo = FALSE, eval = FALSE>>=
%with( hwe.df, hist(p.value, breaks = 1e2) )
%@ 
%\caption{Histogram of Hardy-Weinberg $p$-values}
%\label{hwe-hist}
%\end{figure}
\end{document}
